### ISSUE TITLE
Can't login after setup

### ISSUE THREAD

**Issue by joelis10** [Eleven-am/frames#15]
When I try entering my login details after setting up my server, I get multiple errors until I finally reach the homepage and see this:

![Image](https://github.com/user-attachments/assets/e0675856-6499-4969-9eac-b971bb89a047)

frames-frames-1 logs:
```
[Nest] 109  - 04/01/2025, 9:36:53 AM   ERROR [AuthorizationSocketGuard] User is not authenticated
[Nest] 109  - 04/01/2025, 9:36:54 AM   ERROR [AuthorizationHttpGuard] User is not authenticated
```

Browser (happens on both Chrome and Firefox) logs:

![Image](https://github.com/user-attachments/assets/141934ca-1429-4f54-b57d-d18e8e704a7a)

Is this because I'm accessing it over local IP rather than a HTTPS URL?
Thanks in advance

**Comment by Eleven-am** [comment]
Ah yeah fuck I did not think of that you are gonna have to put it behind a revers proxy and have HTTPS available or else your browser would never accept the cookie sent from the back end

**Comment by Eleven-am** [comment]
fixed the issue, you would need to pull the docker image again thanks

**Comment by joelis10** [comment]
Confirmed as completed 👍🏼

**Comment by Eleven-am** [comment]
Please could you comment on your reddit comment that it is fixed. it would help reassure people that I am working quickly to squash bugs

**Comment by 123mariachi123** [comment]
I still get the "user not authenticated". I use the latest image (tag :latest) and the compose file from the Readme

This is the error
```
frames-1    | [Nest] 94  - 05/12/2025, 10:00:51 AM   ERROR [AuthorizationHttpGuard] User is not authenticated
frames-1    | [Nest] 94  - 05/12/2025, 10:00:51 AM   ERROR [AuthorizationHttpGuard] Error: User is not authenticated
frames-1    | at createBasicError (/usr/src/app/node_modules/@eleven-am/fp/mapper.js:37:31)
frames-1    | at /usr/src/app/node_modules/@eleven-am/authorizer/authorization/authorization.service.js:58:62
frames-1    | at /usr/src/app/node_modules/fp-ts/lib/Either.js:624:56
frames-1    | at async mapTaskEither (/usr/src/app/node_modules/@eleven-am/authorizer/authorization/authorization.constants.js:76:20)
frames-1    | at async GuardsConsumer.tryActivate (/usr/src/app/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
frames-1    | at async canActivateFn (/usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:135:33)
frames-1    | at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:42:31
frames-1    | at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

I tried with and without reverse-proxy so that i had http and https connection (i was hoping this is the issue) but exactly the same error. Anything that i can provide you with to investigate? Thanks

**Comment by Eleven-am** [comment]
Would it be possible to plan a call together so I can set what's up. Right now I'm not so sure what it is

**Comment by 123mariachi123** [comment]
@Eleven-am what timezone are you in? And what app do you suggest for the call?

**Comment by eleven-am** [comment]
I'm in France and I use Discord.
